import type { CourseData } from "@/components/CoursePage";
import { IMG } from "@/lib/images";

export const COURSES: Record<string, CourseData> = {
  "spoken-english": {
    slug: "spoken-english",
    title: "Basic Spoken English",
    tagline: "Speak English with confidence in 6 months — even if you've never spoken a full sentence. Live online, small batches built around gamified practice.",
    category: "English & Career", categoryColor: "brand",
    icon: "mic",
    heroImage: IMG.spokenEnglish, midImage: IMG.womanLaptop, footerImage: IMG.studentLaptop2,
    duration: "6 months · 3 classes/week",
    format: "Live batch · max 6 students",
    price: "₹999/mo",
    outcomes: [
      "Introduce yourself fluently in any social or work setting",
      "Handle daily conversations — shops, travel, phone calls",
      "Build a 2,000+ word everyday vocabulary",
      "Speak with correct grammar, tense and pronunciation",
      "Confidently take part in group discussions",
      "Lose hesitation and stage fear forever",
    ],
    modules: [
      { title: "Foundations & Phonetics", items: ["English sounds & pronunciation drill", "Stress, rhythm, intonation", "Common Indian mistakes — fixed live", "Daily 10-min speaking warm-ups"] },
      { title: "Grammar Without Pain", items: ["Tenses through real conversations", "Articles, prepositions, modals", "Sentence patterns that work everywhere", "Live error-correction games"] },
      { title: "Vocabulary Builder", items: ["1,000+ everyday words & phrases", "Flashcard game sessions", "Phrasal verbs & collocations", "Synonyms for word-power"] },
      { title: "Real-Life Conversations", items: ["Shopping, banking, travel role-plays", "Phone & video calls", "Asking for & giving directions", "Small-talk that doesn't feel small"] },
      { title: "Group Discussions & Debates", items: ["Speak your opinion in 60 seconds", "Active listening exercises", "Disagreeing politely in English", "Live polls & class debates"] },
      { title: "Confidence & Presentation", items: ["Self-introduction mastery", "Storytelling techniques", "Eye contact, body language, voice", "Final live presentation with feedback"] },
    ],
    faqs: [
      { q: "I can barely speak. Will this work for me?", a: "Yes — this is exactly who the course is for. We start from absolute basics and build up step by step in a judgment-free batch." },
      { q: "What's the batch size?", a: "Maximum 6 students per batch so every learner gets real speaking time." },
      { q: "Is the demo really free?", a: "Yes, 100% free. Attend a full live class before deciding." },
      { q: "What if I miss a class?", a: "Every class is recorded and shared. You can also rejoin the same module with the next batch." },
    ],
    testimonials: [
      { quote: "I couldn't speak two lines without freezing. Six months later I gave a 5-min self-intro in front of 30 colleagues.", name: "Anjali Roy", detail: "Spoken English · Teacher, Howrah", waMessage: "Hi, I want the same Spoken English result as Anjali. Can I get a free demo?" },
      { quote: "The gamified flashcard sessions are addictive. I look forward to every class now.", name: "Rakesh Verma", detail: "Spoken English · Shopkeeper, Patna", waMessage: "Hi, please share Spoken English demo details." },
      { quote: "Small batch + real corrections every class. That's what made the difference.", name: "Meera Iyer", detail: "Spoken English · Homemaker, Chennai", waMessage: "Hi, I want to join Spoken English. Free demo please." },
    ],
    metaDescription: "Live online Spoken English classes for Indian learners. 6 months · 3 classes/week · max 6 per batch. ₹999/mo. Free demo on WhatsApp.",
  },
  "business-english": {
    slug: "business-english",
    title: "Business English",
    tagline: "Speak, write and present like a confident professional. Live online, small batches built for working Indians and ambitious freshers.",
    category: "English & Career", categoryColor: "brand",
    icon: "headset",
    heroImage: IMG.businessEnglish, midImage: IMG.womanOffice, footerImage: IMG.presentation,
    duration: "3 months",
    format: "Live batch · max 6 students",
    price: "₹1,199/mo",
    outcomes: [
      "Lead client meetings in English",
      "Write polished emails, proposals & reports",
      "Pitch ideas in 60 seconds",
      "Handle calls & video meetings with confidence",
      "Use professional vocabulary fluently",
      "Negotiate, disagree and persuade — politely",
    ],
    modules: [
      { title: "Professional Emails", items: ["Subject lines that get opened", "Tone: formal vs friendly", "Replying to complaints", "Following up without sounding pushy"] },
      { title: "Meetings & Calls", items: ["Opening & closing meetings", "Agreeing/disagreeing politely", "Phone & video etiquette", "Taking & sending minutes"] },
      { title: "Presentations", items: ["Storyline & structure", "Slides that don't bore", "Voice, pace, body language", "Handling Q&A confidently"] },
      { title: "Negotiation & Persuasion", items: ["The 'soft yes' framework", "Saying no without burning bridges", "Persuasive language patterns", "Live negotiation role-plays"] },
    ],
    metaDescription: "Business English live online classes for working professionals in India. 3 months · max 6 per batch · ₹1,199/mo. Free demo on WhatsApp.",
  },
  "interactive-speaking": {
    slug: "interactive-speaking",
    title: "Interactive Speaking Class",
    tagline: "Daily live speaking practice in a friendly online batch. Designed to build fluency through games, debates and storytelling.",
    category: "English & Career", categoryColor: "brand",
    icon: "headset",
    heroImage: IMG.interactiveSpeaking, midImage: IMG.girlReading, footerImage: IMG.groupClass,
    duration: "3 months",
    format: "Live batch · max 6 students",
    price: "₹999/mo",
    outcomes: ["Speak for 2 minutes on any topic", "Lead group conversations", "Tell stories that hold attention", "Use idioms naturally", "Think in English, not translate", "Win debates with calm logic"],
    modules: [
      { title: "Warm-Ups & Word Games", items: ["Tongue twisters", "1-min just-a-minute", "Word association", "Picture description"] },
      { title: "Story Telling", items: ["The 4-part story formula", "Personal anecdotes", "Adding humour", "Voice modulation"] },
      { title: "Debates & Discussions", items: ["For & against structure", "Active listening", "Polite disagreement", "Closing arguments"] },
      { title: "Role-Plays", items: ["Travel & hotel", "Customer service", "Doctor & patient", "Job networking events"] },
    ],
    metaDescription: "Interactive English speaking classes online. Daily live practice with games, debates and stories. 3 months · max 6 per batch · ₹999/mo.",
  },
  "ielts": {
    slug: "ielts",
    title: "IELTS Preparation",
    tagline: "Target Band 7+ with full-length mocks, speaking labs and live writing feedback — 100% online live, small batches.",
    category: "English & Career", categoryColor: "brand",
    icon: "trophy",
    heroImage: IMG.ielts, midImage: IMG.manStudying, footerImage: IMG.graduation,
    duration: "3 months",
    format: "Live batch · max 6 students",
    price: "₹1,999/mo",
    outcomes: [
      "Score Band 7+ across all four modules",
      "Master Task 1 & Task 2 writing templates",
      "Confidently handle Speaking Part 1, 2 & 3",
      "Crack tricky Listening question types",
      "Time-manage Reading without panic",
      "Take 6+ full-length mock tests with detailed feedback",
    ],
    modules: [
      { title: "Listening Mastery", items: ["Map, form & matching questions", "Section 3 academic discussions", "Note-taking shorthand", "Accent training: UK, AUS, US"] },
      { title: "Reading Strategies", items: ["Skim, scan & deep-read", "True/False/Not Given decoder", "Matching headings tactics", "30-minute mock per week"] },
      { title: "Writing Task 1 & 2", items: ["Academic & GT Task 1 templates", "Task 2 essay structures (5 types)", "Live writing reviewed in class", "Band 7+ vocabulary & connectors"] },
      { title: "Speaking Labs", items: ["Part 1: home, work, hobbies", "Part 2 cue-card structure", "Part 3 abstract discussion", "Mock interviews with feedback"] },
      { title: "Mock Tests & Analysis", items: ["6 full-length timed mocks", "Section-wise weakness map", "Personalised improvement plan", "Predicted band score"] },
    ],
    faqs: [
      { q: "Academic or General Training?", a: "We cover both — your trainer customises drills to your target." },
      { q: "How many mocks?", a: "Minimum 6 full-length mocks." },
    ],
    testimonials: [
      { quote: "Went from 5.5 to 7.5 overall. Writing feedback was a game changer.", name: "Harshit Singh", detail: "IELTS · Now in Toronto", waMessage: "Hi, I saw Harshit's IELTS story. Free demo please." },
      { quote: "Speaking Part 2 used to scare me. The mock interviews killed that fear.", name: "Sneha Das", detail: "IELTS · Now in Sydney", waMessage: "Hi, want to join IELTS. Demo please." },
    ],
    metaDescription: "IELTS Preparation live online — 3 months · max 6 per batch · ₹1,999/mo. 6+ full-length mocks, live writing feedback, speaking labs. Free demo.",
  },
  "interview-prep": {
    slug: "interview-prep",
    title: "Interview Preparation in English",
    tagline: "Walk into your next interview with answers ready, body language sharp, and confidence high. HR + behavioural + communication — all covered live online.",
    category: "English & Career", categoryColor: "brand",
    icon: "target",
    heroImage: IMG.interview, midImage: IMG.manOffice, footerImage: IMG.womanOffice,
    duration: "2 months · intensive",
    format: "Live batch · max 6 students",
    price: "₹1,499/mo",
    outcomes: ["Crack HR rounds confidently", "Answer 'tell me about yourself' in 90 sec", "Handle behavioural questions (STAR)", "Negotiate salary calmly", "Read interviewer cues", "Build a stand-out LinkedIn & resume"],
    modules: [
      { title: "Self-Introduction Mastery", items: ["The 90-second pitch", "Highlighting strengths without bragging", "Story-driven achievements", "Body language & tone"] },
      { title: "HR Rounds", items: ["Most-asked HR questions", "Why this company / why you", "Strengths & weaknesses framing", "Notice period & salary negotiation"] },
      { title: "Behavioural (STAR)", items: ["Situation, Task, Action, Result", "Conflict & failure stories", "Leadership examples", "Team disagreements"] },
      { title: "Resume & LinkedIn", items: ["1-page ATS-friendly resume", "Action-verb bullets", "LinkedIn headline & about", "Recruiter-attracting keywords"] },
      { title: "Mock Interviews", items: ["3 live mock interviews", "Recorded feedback", "Improvement action plan", "Confidence drills"] },
    ],
    metaDescription: "Interview Preparation in English live online — HR, behavioural, mock interviews. 2 months · max 6 per batch · ₹1,499/mo. Free demo on WhatsApp.",
  },
  "career-counselling": {
    slug: "career-counselling",
    title: "Career Counselling",
    tagline: "1:1 online sessions to map your strengths, interests and the right next step — college, course or career switch.",
    category: "English & Career", categoryColor: "brand",
    icon: "compass",
    heroImage: IMG.careerCounselling, midImage: IMG.womanOffice, footerImage: IMG.studentLaptop,
    duration: "3 sessions × 60 min",
    format: "1:1 personalised",
    price: "₹999 total",
    outcomes: ["Discover your strengths & interests", "Shortlist 3 right-fit career paths", "Get a 6-month action plan", "Course/college recommendations", "Resume + LinkedIn review", "Clarity, not confusion"],
    modules: [
      { title: "Discovery", items: ["Strengths inventory", "Interest assessment", "Values & lifestyle goals", "Skill audit"] },
      { title: "Mapping", items: ["3 career path comparison", "Salary & growth research", "Pros & cons grid", "Reality check conversation"] },
      { title: "Action Plan", items: ["6-month milestones", "Course/college options", "Networking targets", "Weekly check-ins (optional)"] },
    ],
    metaDescription: "1:1 Career Counselling online — 3 × 60-min sessions · ₹999 total. Discover, map and act. Free 15-min intro on WhatsApp.",
  },
  "ms-office": {
    slug: "ms-office", title: "MS Office Essentials",
    tagline: "Master Word, Excel, PowerPoint and Outlook — the four tools every office job actually expects. 100% online live, flexible morning/evening/weekend slots.",
    category: "Excel, Data & AI", categoryColor: "indigo",
    icon: "book",
    heroImage: IMG.msoffice, midImage: IMG.womanLaptop, footerImage: IMG.womanOffice,
    duration: "4–6 weeks",
    format: "1:1 personalised live",
    price: "₹999/mo",
    outcomes: [
      "Format professional Word docs with styles & templates",
      "Build Excel sheets, formulas, charts & PivotTables",
      "Design clean, persuasive PowerPoint decks",
      "Run Outlook calendar, email & meetings like a pro",
      "Automate repeat work with Mail Merge & macros",
      "Master 50+ keyboard shortcuts that save hours every week",
    ],
    modules: [
      { title: "Word — Documents that look hired", items: ["Page layout, margins, sections", "Styles, themes & templates", "Tables, headers, footers, page numbers", "Track changes, comments, compare", "Mail Merge (letters, labels, emails)", "Table of Contents & cross-references"] },
      { title: "Excel — Foundations", items: ["Workbook & worksheet hygiene", "Cell formatting, custom number formats", "Top 30 formulas (SUM, IF, COUNTIF, ROUND, TEXT…)", "Lookup intro: VLOOKUP & XLOOKUP", "Sorting, filtering, freeze panes", "Conditional formatting & data bars"] },
      { title: "Excel — PivotTables & Charts", items: ["Build PivotTables from messy data", "Slicers, timelines, calculated fields", "Choosing the right chart type", "Sparklines & combo charts", "Pivot Charts & dashboards basics", "Refresh & external data sources"] },
      { title: "PowerPoint — Decks that persuade", items: ["Slide masters & theme design", "Layout grids & whitespace", "Charts, icons, SmartArt, infographics", "Tasteful animations & transitions", "Speaker notes & rehearsal mode", "Export to PDF, video, handouts"] },
      { title: "Outlook — Inbox Zero", items: ["Inbox Zero workflow & rules", "Calendar, meeting invites, scheduling assistant", "Signatures, templates, quick parts", "Tasks, flags, follow-ups", "Categories, search folders", "Shared mailbox & delegation"] },
      { title: "Cross-app Productivity", items: ["Linking Excel charts into Word/PPT", "Mail Merge from Excel to Word & Outlook", "OneDrive & co-authoring", "Version history & recovery", "Keyboard shortcut mastery", "File hygiene & naming conventions"] },
    ],
    projects: [
      { title: "Kirana Store Monthly Report Pack", brief: "Build a complete monthly report pack for a small Indian kirana store: a Word business letter, an Excel sales-and-stock sheet with PivotTables and charts, and a PowerPoint summary deck for the owner.", deliverable: "Word doc + Excel workbook + PowerPoint deck, all branded with the same theme and shared as a single PDF pack." },
      { title: "Mail Merge Campaign for a Coaching Centre", brief: "Run a personalised admission-offer campaign: clean a 200-row student list in Excel, build the letter template in Word, send it as merged emails via Outlook, and track responses.", deliverable: "Excel data source, Word merge template, Outlook campaign + a 1-page results report." },
    ],
    metaDescription: "MS Office Essentials live online — Word, Excel, PowerPoint, Outlook. 1:1 personalised · ₹999/mo. 2 India-context projects. Free demo on WhatsApp.",
  },
  "master-excel": {
    slug: "master-excel", title: "Master Excel",
    tagline: "From SUM to XLOOKUP, PivotTables, Power Query, DAX-style measures and dashboards — become the Excel person every team needs.",
    category: "Excel, Data & AI", categoryColor: "indigo",
    icon: "chart",
    heroImage: IMG.excel, midImage: IMG.dataDash, footerImage: IMG.presentation,
    duration: "6–8 weeks",
    format: "1:1 personalised live",
    price: "₹1,999/mo",
    outcomes: [
      "Use XLOOKUP, INDEX-MATCH, FILTER & dynamic arrays like a pro",
      "Build PivotTables, calculated fields and slicers that tell stories",
      "Clean messy data automatically with Power Query",
      "Design interactive dashboards with KPI cards & drill-throughs",
      "Write VBA macros for repetitive tasks",
      "Pass any Excel interview test confidently",
    ],
    modules: [
      { title: "Excel Engine & Hygiene", items: ["Workbook structure & best practice", "Named ranges & tables", "Absolute vs relative references", "Cell styles & themes", "Auditing tools & trace precedents", "Performance & file-size tips"] },
      { title: "Formulas — Core", items: ["IF, IFS, AND, OR, NOT", "SUMIFS, COUNTIFS, AVERAGEIFS, MAXIFS", "Text: LEFT, RIGHT, MID, TEXTSPLIT, TEXTJOIN", "Date & time functions, NETWORKDAYS", "ROUND, MROUND, CEILING, FLOOR", "Error handling: IFERROR, IFNA"] },
      { title: "Lookups & Dynamic Arrays", items: ["VLOOKUP vs XLOOKUP vs INDEX-MATCH", "MATCH, OFFSET, INDIRECT", "FILTER, SORT, UNIQUE, SEQUENCE", "Approximate vs exact match", "Multi-criteria lookups", "Two-way lookups"] },
      { title: "PivotTables Mastery", items: ["Build, slice, group", "Calculated fields & items", "Slicers, timelines, report connections", "% of, running totals, ranks", "Pivot Charts & combo charts", "GETPIVOTDATA"] },
      { title: "Power Query (ETL)", items: ["Get & Transform from 20+ sources", "Merge & append queries", "Unpivot & pivot columns", "Clean text, dates, nulls", "Parameters & functions (M intro)", "Refreshable, repeatable pipelines"] },
      { title: "Power Pivot & Data Model", items: ["Star schema in Excel", "Relationships & cardinality", "Measures vs calculated columns", "Time intelligence: YTD, MTD, prior-year", "KPIs & implicit measures", "Connecting Power Query → Power Pivot → Pivot"] },
      { title: "Dashboards & Visualisation", items: ["Dashboard layout principles", "KPI cards & sparklines", "Interactive slicers & form controls", "Conditional formatting tricks", "Icon sets & data bars", "Mobile-friendly layouts"] },
      { title: "Macros & VBA Intro", items: ["Record & edit macros", "Variables, loops, conditions", "Buttons, forms, message boxes", "Cleaning & emailing reports automatically", "Error handling in VBA", "When to (and not to) automate"] },
    ],
    projects: [
      { title: "Kirana / D2C Monthly P&L Dashboard", brief: "A small Indian retailer hands you 12 months of messy sales, expenses and stock data. Clean it in Power Query, model it with Power Pivot, and ship an interactive monthly P&L dashboard with category & city slicers.", deliverable: "Single .xlsx with Power Query pipeline, data model, and a one-page dashboard." },
      { title: "HR Attrition Tracker", brief: "Analyse 1,000+ employee records: attrition by department, tenure bucket, manager and city. Build PivotTables, an attrition heatmap, and an automated monthly refresh.", deliverable: "Excel workbook with refresh button + a 3-slide insight summary." },
    ],
    metaDescription: "Master Excel live online — XLOOKUP, PivotTables, Power Query, dashboards, VBA. 1:1 personalised · ₹1,999/mo. 2 India-context projects.",
  },
  "finance-excel": {
    slug: "finance-excel", title: "Excel for Finance",
    tagline: "The Excel skills CAs, FP&A and finance analysts actually use — 3-statement modelling, NPV/IRR, scenarios, valuation and clean board-ready reporting.",
    category: "Excel, Data & AI", categoryColor: "indigo",
    icon: "rupee",
    heroImage: IMG.finance, midImage: IMG.excel, footerImage: IMG.manOffice,
    duration: "6–8 weeks",
    format: "1:1 personalised live",
    price: "₹1,999/mo",
    outcomes: [
      "Build a clean 3-statement financial model from scratch",
      "Calculate NPV, IRR, MIRR, payback for any project",
      "Run sensitivity, scenario and what-if analysis",
      "Build investor-grade finance dashboards",
      "Audit and error-proof other people's models",
      "Speak the language of FP&A, equity research and corp-fin teams",
    ],
    modules: [
      { title: "Finance Foundations in Excel", items: ["Time value of money", "PMT, RATE, NPER, PV, FV", "NPV, IRR, MIRR, XNPV, XIRR", "Effective vs nominal rates", "Amortisation schedules", "Loan & lease calculations"] },
      { title: "Financial Modelling — Build", items: ["Modelling principles & colour coding", "Revenue drivers & assumption sheets", "Cost build-up: fixed vs variable", "Working capital schedule", "Debt schedule & interest", "Tax & depreciation schedules"] },
      { title: "3-Statement Linking", items: ["Income Statement build", "Balance Sheet build & checks", "Cash Flow Statement linking", "Plug & balance checks", "Circularity handling (iterative calc)", "Audit & error checks"] },
      { title: "Valuation", items: ["Discounted Cash Flow (DCF)", "WACC build-up", "Terminal value (Gordon / exit multiple)", "Comparable company analysis", "Precedent transactions", "Football-field summary chart"] },
      { title: "Scenarios & Sensitivity", items: ["Data Tables (1-var & 2-var)", "Scenario Manager", "Goal Seek & Solver", "Tornado & spider charts", "Monte Carlo intro", "Risk scoring framework"] },
      { title: "Finance Dashboards", items: ["KPI design for finance", "Variance analysis (actual vs budget)", "Driver tree & waterfall charts", "Executive summary view", "Investor pitch dashboard", "Board-ready formatting"] },
      { title: "Real-World FP&A Workflow", items: ["Monthly close & rolling forecast", "Budget vs actual reporting", "Headcount & cost-centre reports", "Power Query for actuals refresh", "Best-practice model templates", "Reviewing & auditing legacy models"] },
    ],
    projects: [
      { title: "SIP, Loan EMI & Goal Planner", brief: "Build a personal finance planner an Indian salaried professional could use: SIP corpus calculator, home-loan EMI schedule, and a goal-based investing tracker — all with sensitivity tables.", deliverable: "Excel workbook with assumption sheet, 3 dashboards and a 1-page printable summary." },
      { title: "3-Statement Model for an Indian SME", brief: "Build a fully linked 3-statement model + DCF valuation for a mid-sized Indian SME (e.g. a regional FMCG brand). Includes scenarios, sensitivity and a football-field valuation summary.", deliverable: "Single .xlsx model + a 5-slide investor summary deck." },
    ],
    metaDescription: "Excel for Finance live online — 3-statement modelling, NPV/IRR, DCF, dashboards. 1:1 personalised · ₹1,999/mo. 2 India-context projects.",
  },
  "python": {
    slug: "python", title: "Master Python",
    tagline: "Go from zero to job-ready Python — automation, data analysis with Pandas, visualisation, and two India-context portfolio projects you can actually show.",
    category: "Excel, Data & AI", categoryColor: "indigo",
    icon: "code",
    heroImage: IMG.python, midImage: IMG.code, footerImage: IMG.studentLaptop,
    duration: "10–12 weeks",
    format: "1:1 personalised live",
    price: "₹1,999/mo",
    outcomes: [
      "Write clean, idiomatic Python from scratch",
      "Automate Excel, files, PDFs and emails",
      "Wrangle and analyse data with Pandas",
      "Visualise data with Matplotlib & Seaborn",
      "Scrape and clean public web data",
      "Ship 2 portfolio projects to GitHub with notebooks",
    ],
    modules: [
      { title: "Python Foundations", items: ["Setup: Python, VS Code, Jupyter", "Variables, types, operators", "Strings, f-strings, formatting", "Lists, dicts, sets, tuples", "If/else, for/while loops, comprehensions", "Functions, *args/**kwargs, scope"] },
      { title: "Pythonic Code & OOP", items: ["Modules & packages", "Files & exceptions", "Generators & iterators", "Classes, methods, dunder methods", "Inheritance basics", "Testing with pytest (intro)"] },
      { title: "Automation in Real Life", items: ["openpyxl: read/write Excel", "Working with CSV, JSON, XML", "PDF extraction with pdfplumber", "Sending emails via SMTP", "File system & folder automation", "Scheduling scripts (cron / Task Scheduler)"] },
      { title: "Web & APIs", items: ["requests: calling REST APIs", "BeautifulSoup web scraping", "Working with JSON responses", "Authentication & rate limits", "Scraping ethics & robots.txt", "Saving scraped data to CSV/DB"] },
      { title: "Pandas for Data", items: ["DataFrames & Series fundamentals", "Reading CSV, Excel, SQL, JSON", "Cleaning: nulls, dtypes, duplicates", "Filtering, sorting, indexing", "groupby, agg, pivot_table", "merge, join, concat & reshape"] },
      { title: "Time Series & EDA", items: ["Datetime handling & resampling", "Rolling windows & moving averages", "Profiling with pandas-profiling", "Outlier detection", "Correlation & distributions", "Storytelling with EDA"] },
      { title: "Visualisation", items: ["Matplotlib essentials", "Seaborn for stats plots", "Plotly for interactive charts", "Saving publication-ready figures", "Dashboarding with Streamlit (intro)", "Storytelling with plots"] },
      { title: "Career Sprint", items: ["GitHub: repos, README, gitignore", "Notebook hygiene & docstrings", "Resume-ready project structure", "Top 30 Python interview questions", "Live mock interview", "Portfolio walk-through"] },
    ],
    projects: [
      { title: "Zomato Bangalore Restaurants — EDA", brief: "Analyse 50k+ Zomato Bangalore listings: clean messy text, parse cuisines & prices, find cuisine-wise rating patterns, location heatmaps and top-value-for-money pockets.", deliverable: "Jupyter notebook + 4–6 polished charts + a 1-page insight report, pushed to GitHub." },
      { title: "Nifty 50 Returns Analyser", brief: "Pull 5 years of Nifty 50 stock data, compute daily/monthly returns, volatility, rolling Sharpe and a simple momentum signal — then visualise the leaderboard.", deliverable: "Notebook + reusable .py module + interactive Plotly dashboard." },
    ],
    metaDescription: "Master Python live online — automation, Pandas, visualisation, scraping. 1:1 personalised · ₹1,999/mo. 2 India-context capstone projects.",
  },
  "power-bi": {
    slug: "power-bi", title: "Power BI Mastery (PL-300)",
    tagline: "Build interactive dashboards, write DAX confidently, model star-schemas, and prep for the Microsoft PL-300 certification — all live with India-context data.",
    category: "Excel, Data & AI", categoryColor: "indigo",
    icon: "trend",
    heroImage: IMG.powerbi, midImage: IMG.dataDash, footerImage: IMG.presentation,
    duration: "8–10 weeks",
    format: "1:1 personalised live",
    price: "₹1,999/mo",
    outcomes: [
      "Build 3+ portfolio dashboards end-to-end",
      "Write DAX measures without fear (CALCULATE, FILTER, time-intelligence)",
      "Model star-schema data the right way",
      "Use Power Query for ETL from any source",
      "Publish, share and secure reports on Power BI Service",
      "Pass PL-300 on first attempt",
    ],
    modules: [
      { title: "Power BI Desktop & Service", items: ["Desktop vs Service vs Mobile", "Workspaces, apps, datasets", "Connecting to 30+ data sources", "Refresh schedules & gateways", "Row-level security basics", "Sharing & permissions"] },
      { title: "Power Query (ETL)", items: ["Get & Transform anything", "Merge, append, group", "Pivot/unpivot & fill", "Parameters & query functions", "M language essentials", "Performance & query folding"] },
      { title: "Data Modelling", items: ["Star schema vs snowflake", "Fact vs dimension tables", "Relationships, cardinality, cross-filter", "Date table best practices", "Hide/show fields, hierarchies", "Model size & VertiPaq tips"] },
      { title: "DAX — Foundations", items: ["Calculated columns vs measures", "Row vs filter context", "CALCULATE & FILTER", "ALL, ALLEXCEPT, REMOVEFILTERS", "Iterators: SUMX, AVERAGEX", "Variables & readability"] },
      { title: "DAX — Time Intelligence", items: ["SAMEPERIODLASTYEAR, DATEADD", "DATESYTD, DATESMTD, DATESQTD", "Rolling 12-month measures", "Period-over-period growth", "Custom calendars / fiscal year", "Last refresh & freshness checks"] },
      { title: "Visualisations & UX", items: ["Choosing the right chart", "Custom themes & JSON theming", "Drillthrough, drill-down, bookmarks", "Tooltips & report-page tooltips", "Mobile layouts", "Accessibility & contrast"] },
      { title: "Performance & Governance", items: ["Performance Analyzer", "Reducing model size", "Aggregations & composite models", "Deployment pipelines", "Workspace governance", "Dataset documentation"] },
      { title: "PL-300 Exam Prep", items: ["Full exam blueprint walk-through", "200+ practice questions", "2 timed full-length mocks", "Common trick questions", "Last-mile tips & exam-day plan", "Post-exam career roadmap"] },
    ],
    projects: [
      { title: "Swiggy Orders KPI Dashboard", brief: "Model a Swiggy-style orders dataset (orders, restaurants, riders, cities). Build a 3-page report: business KPIs, city/cuisine deep-dive, and operational rider performance — with DAX time-intelligence and drillthrough.", deliverable: ".pbix file + published Power BI Service report + 1-page insight write-up." },
      { title: "Sales Pipeline Executive Report", brief: "Build a B2B sales pipeline dashboard for an Indian SaaS startup: funnel stages, owner performance, regional split, forecast vs actual, with row-level security per sales manager.", deliverable: ".pbix + published app + RLS setup + 3-slide stakeholder summary." },
    ],
    metaDescription: "Power BI live online — DAX, modelling, dashboards, PL-300 prep. 1:1 personalised · ₹1,999/mo. 2 India-context capstone projects.",
  },
  "prompt-engineering": {
    slug: "prompt-engineering", title: "Prompt Engineering with Claude & ChatGPT",
    tagline: "Make AI work for you — students, teachers, marketers, office professionals. Master prompting, workflows and AI tools that 10× your output. Basic coding knowledge required.",
    category: "Excel, Data & AI", categoryColor: "indigo",
    icon: "spark",
    heroImage: IMG.aiPrompt, midImage: IMG.aiPrompt, footerImage: IMG.studentLaptop,
    duration: "2 months",
    format: "1:1 personalised live",
    price: "₹1,199/mo",
    outcomes: [
      "Write precise, role-based prompts that actually work",
      "Build reusable prompt templates for daily work",
      "Use Claude, ChatGPT and Gemini for research, writing & analysis",
      "Automate routine office, study and marketing tasks",
      "Apply chain-of-thought, few-shot and structured-output patterns",
      "Spot and fix hallucinations — use AI responsibly",
    ],
    modules: [
      { title: "AI Foundations", items: ["LLM basics: tokens, context window, temperature", "Claude vs ChatGPT vs Gemini — when to use which", "Free vs paid plans — practical guide", "Setting up your AI workspace", "Privacy, copyright & responsible use"] },
      { title: "Prompting Patterns", items: ["Zero-shot, few-shot, chain-of-thought", "Role + task + context + format framework", "System prompts & persistent personas", "Structured output (JSON, tables, markdown)", "Iterative refinement loops"] },
      { title: "Prompting for Students", items: ["Research summaries & literature reviews", "Step-by-step problem-solving tutors", "Essay drafting & feedback prompts", "Flashcard generation & exam prep", "Honest-use guardrails for assignments"] },
      { title: "Prompting for Teachers & Marketers", items: ["Lesson plans, worksheets & rubrics", "Email & social copy generation", "Audience-tone rewriting", "Campaign ideation & A/B variants", "SEO blog outlines"] },
      { title: "Office & Productivity Workflows", items: ["Meeting notes → action items", "Long PDF & report summarisation", "Excel formula & SQL generation", "Email triage & reply templates", "Custom GPTs & Claude Projects"] },
      { title: "Capstone & Best Practices", items: ["Build your personal prompt library", "Evaluating AI output — quality checklist", "Hallucination spotting drills", "Cost & speed optimisation", "Live capstone showcase"] },
    ],
    projects: [
      { title: "Personal AI Productivity Stack", brief: "Build a personalised prompt library (50+ prompts) covering your daily work — research, writing, summarisation, planning — organised in Claude Projects or Custom GPTs with reusable templates.", deliverable: "Documented prompt library + shareable Claude Project / Custom GPT + a 1-page how-I-use-AI guide." },
      { title: "AI-Powered Mini Marketing Campaign", brief: "Run a complete mini campaign for a small Indian brand: research with AI, generate 10 social posts, 3 email variants and an SEO blog outline — all with measurable prompt iterations.", deliverable: "Campaign pack (copy + visuals brief + posting calendar) + prompt journal showing your iterations." },
    ],
    metaDescription: "Prompt Engineering live online with Claude & ChatGPT — for students, teachers, marketers, office workers. 1:1 · 2 months · ₹1,199/mo.",
  },
  "ai-builder": {
    slug: "ai-builder", title: "Building with Claude API, OpenAI & Agentic AI",
    tagline: "For analysts and developers. Build real AI apps with Claude API, OpenAI, Claude Code, Amazon Bedrock, GitHub Copilot and Cloudflare Pages — including RAG, MCP and agentic workflows.",
    category: "Excel, Data & AI", categoryColor: "indigo",
    icon: "rocket",
    heroImage: IMG.aiBuild, midImage: IMG.aiBuild, footerImage: IMG.code,
    duration: "2 months",
    format: "1:1 personalised live",
    price: "₹1,499/mo",
    outcomes: [
      "Call Claude & OpenAI APIs from Python/Node confidently",
      "Build a working RAG pipeline over your own documents",
      "Ship a deployed AI web app on Cloudflare Pages",
      "Use Claude Code & GitHub Copilot to 10× your dev speed",
      "Wire up MCP servers and tool-use for real automations",
      "Design simple agentic workflows that actually work",
    ],
    modules: [
      { title: "API Foundations", items: ["Auth, rate limits, pricing across providers", "Claude API: messages, system, tools", "OpenAI API: chat, embeddings, structured output", "Streaming responses & token cost control", "Prompt caching & batch APIs"] },
      { title: "Claude Code & Copilot Workflows", items: ["Claude Code setup & project conventions", "GitHub Copilot in VS Code: best patterns", "Refactor, test-gen and code-review prompts", "Spec-driven development with AI", "Pair-programming with an agent"] },
      { title: "RAG (Retrieval-Augmented Generation)", items: ["Chunking strategies for real documents", "Embeddings & vector stores (pgvector, Chroma)", "Hybrid search & re-ranking", "Citation & grounding patterns", "Evaluating RAG quality"] },
      { title: "MCP & Tool Use", items: ["Model Context Protocol basics", "Building a simple MCP server", "Tool/function calling end-to-end", "Connecting AI to Excel, files, SQL, web", "Safety: scoping permissions"] },
      { title: "Agentic AI", items: ["Single-agent loops vs multi-agent", "Planning, reflection & self-correction", "When agents work (and when they don't)", "Cost & latency budgets", "Real Indian use-cases (support, ops, research)"] },
      { title: "Deploy: Bedrock & Cloudflare", items: ["Amazon Bedrock model access & basics", "Cloudflare Pages + Workers AI", "Edge functions & streaming responses", "Secrets, observability & cost dashboards", "Going live with a public demo URL"] },
    ],
    projects: [
      { title: "Document Q&A RAG App", brief: "Build a working RAG app over a folder of Indian regulatory PDFs (e.g. SEBI, RBI circulars): ingest, embed, store in pgvector, and serve a chat UI with grounded citations.", deliverable: "Deployed app on Cloudflare Pages + repo with RAG pipeline + 1-page architecture write-up." },
      { title: "Agentic Workflow with MCP & Tools", brief: "Design a small agent that reads an Excel sheet of customer complaints, classifies them, drafts replies via Claude, and logs results back to the sheet through an MCP server.", deliverable: "Working agent + MCP server code + a short Loom showing it run end-to-end." },
    ],
    metaDescription: "Build with Claude API, OpenAI, Bedrock, MCP & agentic AI — live online for analysts & developers. 1:1 · 2 months · ₹1,499/mo.",
  },
  "ai-projects": {
    slug: "ai-projects", title: "AI Projects — Academic & Industrial",
    tagline: "Project-based course for academic theses and industry capstones. Work hands-on with Claude, Claude Code, APIs, MCP, agentic AI and workflow management.",
    category: "Excel, Data & AI", categoryColor: "indigo",
    icon: "trophy",
    heroImage: IMG.aiProject, midImage: IMG.aiProject, footerImage: IMG.graduation,
    duration: "2 months · project-based",
    format: "1:1 personalised live",
    price: "₹1,999/mo",
    outcomes: [
      "Scope and deliver a complete AI project end-to-end",
      "Choose the right architecture: prompt vs RAG vs agent",
      "Write clean, reproducible code with Claude Code",
      "Document, evaluate and present your work",
      "Build an industry-grade portfolio piece",
      "Defend your project in viva or stakeholder review",
    ],
    modules: [
      { title: "Project Scoping", items: ["Problem framing & success metrics", "Academic vs industrial scope", "Data, compute & cost budgeting", "Risk and ethics checklist", "Milestone plan with weekly check-ins"] },
      { title: "Architecture & Stack Selection", items: ["When prompt-only is enough", "When to add RAG", "When agents earn their keep", "Provider mix (Claude, OpenAI, Bedrock)", "Hosting on Cloudflare / Vercel"] },
      { title: "Build with Claude Code", items: ["Repo conventions & docs-first development", "Test-driven AI coding", "Eval harness for prompts & models", "Version control of prompts & datasets", "Cost & latency tracking"] },
      { title: "MCP, Tools & Workflow Management", items: ["Wiring tools to your domain (sheets, DB, APIs)", "Multi-step workflow orchestration", "Queueing, retries, observability", "Human-in-the-loop checkpoints", "Failure modes & guardrails"] },
      { title: "Evaluation & Reporting", items: ["Quantitative + qualitative eval", "Building a results dashboard", "Writing a clear technical report", "Slide deck for stakeholders / viva", "Reproducibility & handover"] },
    ],
    projects: [
      { title: "Academic Capstone (your choice)", brief: "Define and ship a publishable-quality AI project aligned to your thesis or coursework — e.g. RAG over Indian agricultural reports, an LLM tutor for board exams, or a research-paper summariser with eval.", deliverable: "GitHub repo + technical report + a 10-min defence deck." },
      { title: "Industrial Pilot", brief: "Build a real workflow for a small Indian SME or a hypothetical employer: agentic support triage, AI sales-research bot, or an internal knowledge assistant — with metrics, cost and rollout plan.", deliverable: "Deployed pilot + ROI & cost report + a 5-slide leadership pitch." },
    ],
    metaDescription: "AI Projects live online — academic & industrial capstones with Claude, MCP, agentic AI & workflow management. 1:1 · 2 months · ₹1,999/mo.",
  },
};
