/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyUsRouteImport } from './routes/why-us'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as EnglishCareerRouteImport } from './routes/english-career'
import { Route as CourseSpokenEnglishRouteImport } from './routes/course-spoken-english'
import { Route as CourseInterviewPrepRouteImport } from './routes/course-interview-prep'
import { Route as CourseInteractiveSpeakingRouteImport } from './routes/course-interactive-speaking'
import { Route as CourseIeltsRouteImport } from './routes/course-ielts'
import { Route as CourseCareerCounsellingRouteImport } from './routes/course-career-counselling'
import { Route as CourseBusinessEnglishRouteImport } from './routes/course-business-english'
import { Route as BookFreeDemoRouteImport } from './routes/book-free-demo'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'

const WhyUsRoute = WhyUsRouteImport.update({
  id: '/why-us',
  path: '/why-us',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishCareerRoute = EnglishCareerRouteImport.update({
  id: '/english-career',
  path: '/english-career',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseSpokenEnglishRoute = CourseSpokenEnglishRouteImport.update({
  id: '/course-spoken-english',
  path: '/course-spoken-english',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseInterviewPrepRoute = CourseInterviewPrepRouteImport.update({
  id: '/course-interview-prep',
  path: '/course-interview-prep',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseInteractiveSpeakingRoute =
  CourseInteractiveSpeakingRouteImport.update({
    id: '/course-interactive-speaking',
    path: '/course-interactive-speaking',
    getParentRoute: () => rootRouteImport,
  } as any)
const CourseIeltsRoute = CourseIeltsRouteImport.update({
  id: '/course-ielts',
  path: '/course-ielts',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCareerCounsellingRoute = CourseCareerCounsellingRouteImport.update({
  id: '/course-career-counselling',
  path: '/course-career-counselling',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseBusinessEnglishRoute = CourseBusinessEnglishRouteImport.update({
  id: '/course-business-english',
  path: '/course-business-english',
  getParentRoute: () => rootRouteImport,
} as any)
const BookFreeDemoRoute = BookFreeDemoRouteImport.update({
  id: '/book-free-demo',
  path: '/book-free-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/blog': typeof BlogRoute
  '/book-free-demo': typeof BookFreeDemoRoute
  '/course-business-english': typeof CourseBusinessEnglishRoute
  '/course-career-counselling': typeof CourseCareerCounsellingRoute
  '/course-ielts': typeof CourseIeltsRoute
  '/course-interactive-speaking': typeof CourseInteractiveSpeakingRoute
  '/course-interview-prep': typeof CourseInterviewPrepRoute
  '/course-spoken-english': typeof CourseSpokenEnglishRoute
  '/english-career': typeof EnglishCareerRoute
  '/founder': typeof FounderRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/why-us': typeof WhyUsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/blog': typeof BlogRoute
  '/book-free-demo': typeof BookFreeDemoRoute
  '/course-business-english': typeof CourseBusinessEnglishRoute
  '/course-career-counselling': typeof CourseCareerCounsellingRoute
  '/course-ielts': typeof CourseIeltsRoute
  '/course-interactive-speaking': typeof CourseInteractiveSpeakingRoute
  '/course-interview-prep': typeof CourseInterviewPrepRoute
  '/course-spoken-english': typeof CourseSpokenEnglishRoute
  '/english-career': typeof EnglishCareerRoute
  '/founder': typeof FounderRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/why-us': typeof WhyUsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/blog': typeof BlogRoute
  '/book-free-demo': typeof BookFreeDemoRoute
  '/course-business-english': typeof CourseBusinessEnglishRoute
  '/course-career-counselling': typeof CourseCareerCounsellingRoute
  '/course-ielts': typeof CourseIeltsRoute
  '/course-interactive-speaking': typeof CourseInteractiveSpeakingRoute
  '/course-interview-prep': typeof CourseInterviewPrepRoute
  '/course-spoken-english': typeof CourseSpokenEnglishRoute
  '/english-career': typeof EnglishCareerRoute
  '/founder': typeof FounderRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/why-us': typeof WhyUsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/blog'
    | '/book-free-demo'
    | '/course-business-english'
    | '/course-career-counselling'
    | '/course-ielts'
    | '/course-interactive-speaking'
    | '/course-interview-prep'
    | '/course-spoken-english'
    | '/english-career'
    | '/founder'
    | '/success-stories'
    | '/why-us'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/blog'
    | '/book-free-demo'
    | '/course-business-english'
    | '/course-career-counselling'
    | '/course-ielts'
    | '/course-interactive-speaking'
    | '/course-interview-prep'
    | '/course-spoken-english'
    | '/english-career'
    | '/founder'
    | '/success-stories'
    | '/why-us'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/blog'
    | '/book-free-demo'
    | '/course-business-english'
    | '/course-career-counselling'
    | '/course-ielts'
    | '/course-interactive-speaking'
    | '/course-interview-prep'
    | '/course-spoken-english'
    | '/english-career'
    | '/founder'
    | '/success-stories'
    | '/why-us'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  BlogRoute: typeof BlogRoute
  BookFreeDemoRoute: typeof BookFreeDemoRoute
  CourseBusinessEnglishRoute: typeof CourseBusinessEnglishRoute
  CourseCareerCounsellingRoute: typeof CourseCareerCounsellingRoute
  CourseIeltsRoute: typeof CourseIeltsRoute
  CourseInteractiveSpeakingRoute: typeof CourseInteractiveSpeakingRoute
  CourseInterviewPrepRoute: typeof CourseInterviewPrepRoute
  CourseSpokenEnglishRoute: typeof CourseSpokenEnglishRoute
  EnglishCareerRoute: typeof EnglishCareerRoute
  FounderRoute: typeof FounderRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  WhyUsRoute: typeof WhyUsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-us': {
      id: '/why-us'
      path: '/why-us'
      fullPath: '/why-us'
      preLoaderRoute: typeof WhyUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english-career': {
      id: '/english-career'
      path: '/english-career'
      fullPath: '/english-career'
      preLoaderRoute: typeof EnglishCareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course-spoken-english': {
      id: '/course-spoken-english'
      path: '/course-spoken-english'
      fullPath: '/course-spoken-english'
      preLoaderRoute: typeof CourseSpokenEnglishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course-interview-prep': {
      id: '/course-interview-prep'
      path: '/course-interview-prep'
      fullPath: '/course-interview-prep'
      preLoaderRoute: typeof CourseInterviewPrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course-interactive-speaking': {
      id: '/course-interactive-speaking'
      path: '/course-interactive-speaking'
      fullPath: '/course-interactive-speaking'
      preLoaderRoute: typeof CourseInteractiveSpeakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course-ielts': {
      id: '/course-ielts'
      path: '/course-ielts'
      fullPath: '/course-ielts'
      preLoaderRoute: typeof CourseIeltsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course-career-counselling': {
      id: '/course-career-counselling'
      path: '/course-career-counselling'
      fullPath: '/course-career-counselling'
      preLoaderRoute: typeof CourseCareerCounsellingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course-business-english': {
      id: '/course-business-english'
      path: '/course-business-english'
      fullPath: '/course-business-english'
      preLoaderRoute: typeof CourseBusinessEnglishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-free-demo': {
      id: '/book-free-demo'
      path: '/book-free-demo'
      fullPath: '/book-free-demo'
      preLoaderRoute: typeof BookFreeDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  BlogRoute: BlogRoute,
  BookFreeDemoRoute: BookFreeDemoRoute,
  CourseBusinessEnglishRoute: CourseBusinessEnglishRoute,
  CourseCareerCounsellingRoute: CourseCareerCounsellingRoute,
  CourseIeltsRoute: CourseIeltsRoute,
  CourseInteractiveSpeakingRoute: CourseInteractiveSpeakingRoute,
  CourseInterviewPrepRoute: CourseInterviewPrepRoute,
  CourseSpokenEnglishRoute: CourseSpokenEnglishRoute,
  EnglishCareerRoute: EnglishCareerRoute,
  FounderRoute: FounderRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
  WhyUsRoute: WhyUsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
