/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as BestOnlineSpokenEnglishClassesIndiaRouteImport } from './routes/best-online-spoken-english-classes-india'
import { Route as BookFreeDemoRouteImport } from './routes/book-free-demo'
import { Route as CourseBusinessEnglishRouteImport } from './routes/course-business-english'
import { Route as CourseCareerCounsellingRouteImport } from './routes/course-career-counselling'
import { Route as CourseIeltsRouteImport } from './routes/course-ielts'
import { Route as CourseInteractiveSpeakingRouteImport } from './routes/course-interactive-speaking'
import { Route as CourseInterviewPrepRouteImport } from './routes/course-interview-prep'
import { Route as CourseKidsEnglishRouteImport } from './routes/course-kids-english'
import { Route as CourseSpokenEnglishRouteImport } from './routes/course-spoken-english'
import { Route as EnglishCareerRouteImport } from './routes/english-career'
import { Route as EnglishClassFeesIndiaRouteImport } from './routes/english-class-fees-india'
import { Route as EnglishForClientCallsIndiaRouteImport } from './routes/english-for-client-calls-india'
import { Route as EnglishForItProfessionalsIndiaRouteImport } from './routes/english-for-it-professionals-india'
import { Route as EnglishForPresentationsIndiaRouteImport } from './routes/english-for-presentations-india'
import { Route as EnglishForWorkingProfessionalsIndiaRouteImport } from './routes/english-for-working-professionals-india'
import { Route as EnglishHindiBengaliMediumRouteImport } from './routes/english-hindi-bengali-medium'
import { Route as EnglishInstituteComparisonIndiaRouteImport } from './routes/english-institute-comparison-india'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as FreeEnglishSpeakingPracticeVsPaidClassRouteImport } from './routes/free-english-speaking-practice-vs-paid-class'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as HowLongToLearnSpokenEnglishRouteImport } from './routes/how-long-to-learn-spoken-english'
import { Route as HowToSpeakEnglishFluentlyRouteImport } from './routes/how-to-speak-english-fluently'
import { Route as IeltsCoachingFeesIndiaRouteImport } from './routes/ielts-coaching-fees-india'
import { Route as InteractiveEnglishClassHesitationRouteImport } from './routes/interactive-english-class-hesitation'
import { Route as OnlineVsOfflineSpokenEnglishClassesRouteImport } from './routes/online-vs-offline-spoken-english-classes'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as SpokenBusinessOrInteractiveEnglishRouteImport } from './routes/spoken-business-or-interactive-english'
import { Route as SpokenEnglishClassesAhmedabadRouteImport } from './routes/spoken-english-classes-ahmedabad'
import { Route as SpokenEnglishClassesBengaluruRouteImport } from './routes/spoken-english-classes-bengaluru'
import { Route as SpokenEnglishClassesChennaiRouteImport } from './routes/spoken-english-classes-chennai'
import { Route as SpokenEnglishClassesCoimbatoreRouteImport } from './routes/spoken-english-classes-coimbatore'
import { Route as SpokenEnglishClassesDelhiRouteImport } from './routes/spoken-english-classes-delhi'
import { Route as SpokenEnglishClassesGuwahatiRouteImport } from './routes/spoken-english-classes-guwahati'
import { Route as SpokenEnglishClassesHyderabadRouteImport } from './routes/spoken-english-classes-hyderabad'
import { Route as SpokenEnglishClassesKochiRouteImport } from './routes/spoken-english-classes-kochi'
import { Route as SpokenEnglishClassesKolkataRouteImport } from './routes/spoken-english-classes-kolkata'
import { Route as SpokenEnglishClassesMumbaiRouteImport } from './routes/spoken-english-classes-mumbai'
import { Route as SpokenEnglishClassesNagpurRouteImport } from './routes/spoken-english-classes-nagpur'
import { Route as SpokenEnglishClassesPatnaRouteImport } from './routes/spoken-english-classes-patna'
import { Route as SpokenEnglishClassesPuneRouteImport } from './routes/spoken-english-classes-pune'
import { Route as SpokenEnglishClassesSuratRouteImport } from './routes/spoken-english-classes-surat'
import { Route as SpokenEnglishClassesVisakhapatnamRouteImport } from './routes/spoken-english-classes-visakhapatnam'
import { Route as SpokenEnglishForBeginnersIndiaRouteImport } from './routes/spoken-english-for-beginners-india'
import { Route as SpokenEnglishForFreshersIndiaRouteImport } from './routes/spoken-english-for-freshers-india'
import { Route as SpokenEnglishForHomemakersIndiaRouteImport } from './routes/spoken-english-for-homemakers-india'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WhyUsRouteImport } from './routes/why-us'
import { Route as WorkplaceEnglishCourseOnlineIndiaRouteImport } from './routes/workplace-english-course-online-india'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const BestOnlineSpokenEnglishClassesIndiaRoute =
  BestOnlineSpokenEnglishClassesIndiaRouteImport.update({
    id: '/best-online-spoken-english-classes-india',
    path: '/best-online-spoken-english-classes-india',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookFreeDemoRoute = BookFreeDemoRouteImport.update({
  id: '/book-free-demo',
  path: '/book-free-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseBusinessEnglishRoute = CourseBusinessEnglishRouteImport.update({
  id: '/course-business-english',
  path: '/course-business-english',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCareerCounsellingRoute = CourseCareerCounsellingRouteImport.update({
  id: '/course-career-counselling',
  path: '/course-career-counselling',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseIeltsRoute = CourseIeltsRouteImport.update({
  id: '/course-ielts',
  path: '/course-ielts',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseInteractiveSpeakingRoute =
  CourseInteractiveSpeakingRouteImport.update({
    id: '/course-interactive-speaking',
    path: '/course-interactive-speaking',
    getParentRoute: () => rootRouteImport,
  } as any)
const CourseInterviewPrepRoute = CourseInterviewPrepRouteImport.update({
  id: '/course-interview-prep',
  path: '/course-interview-prep',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseKidsEnglishRoute = CourseKidsEnglishRouteImport.update({
  id: '/course-kids-english',
  path: '/course-kids-english',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseSpokenEnglishRoute = CourseSpokenEnglishRouteImport.update({
  id: '/course-spoken-english',
  path: '/course-spoken-english',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishCareerRoute = EnglishCareerRouteImport.update({
  id: '/english-career',
  path: '/english-career',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishClassFeesIndiaRoute = EnglishClassFeesIndiaRouteImport.update({
  id: '/english-class-fees-india',
  path: '/english-class-fees-india',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishForClientCallsIndiaRoute =
  EnglishForClientCallsIndiaRouteImport.update({
    id: '/english-for-client-calls-india',
    path: '/english-for-client-calls-india',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnglishForItProfessionalsIndiaRoute =
  EnglishForItProfessionalsIndiaRouteImport.update({
    id: '/english-for-it-professionals-india',
    path: '/english-for-it-professionals-india',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnglishForPresentationsIndiaRoute =
  EnglishForPresentationsIndiaRouteImport.update({
    id: '/english-for-presentations-india',
    path: '/english-for-presentations-india',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnglishForWorkingProfessionalsIndiaRoute =
  EnglishForWorkingProfessionalsIndiaRouteImport.update({
    id: '/english-for-working-professionals-india',
    path: '/english-for-working-professionals-india',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnglishHindiBengaliMediumRoute =
  EnglishHindiBengaliMediumRouteImport.update({
    id: '/english-hindi-bengali-medium',
    path: '/english-hindi-bengali-medium',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnglishInstituteComparisonIndiaRoute =
  EnglishInstituteComparisonIndiaRouteImport.update({
    id: '/english-institute-comparison-india',
    path: '/english-institute-comparison-india',
    getParentRoute: () => rootRouteImport,
  } as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeEnglishSpeakingPracticeVsPaidClassRoute =
  FreeEnglishSpeakingPracticeVsPaidClassRouteImport.update({
    id: '/free-english-speaking-practice-vs-paid-class',
    path: '/free-english-speaking-practice-vs-paid-class',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const HowLongToLearnSpokenEnglishRoute =
  HowLongToLearnSpokenEnglishRouteImport.update({
    id: '/how-long-to-learn-spoken-english',
    path: '/how-long-to-learn-spoken-english',
    getParentRoute: () => rootRouteImport,
  } as any)
const HowToSpeakEnglishFluentlyRoute =
  HowToSpeakEnglishFluentlyRouteImport.update({
    id: '/how-to-speak-english-fluently',
    path: '/how-to-speak-english-fluently',
    getParentRoute: () => rootRouteImport,
  } as any)
const IeltsCoachingFeesIndiaRoute = IeltsCoachingFeesIndiaRouteImport.update({
  id: '/ielts-coaching-fees-india',
  path: '/ielts-coaching-fees-india',
  getParentRoute: () => rootRouteImport,
} as any)
const InteractiveEnglishClassHesitationRoute =
  InteractiveEnglishClassHesitationRouteImport.update({
    id: '/interactive-english-class-hesitation',
    path: '/interactive-english-class-hesitation',
    getParentRoute: () => rootRouteImport,
  } as any)
const OnlineVsOfflineSpokenEnglishClassesRoute =
  OnlineVsOfflineSpokenEnglishClassesRouteImport.update({
    id: '/online-vs-offline-spoken-english-classes',
    path: '/online-vs-offline-spoken-english-classes',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const SpokenBusinessOrInteractiveEnglishRoute =
  SpokenBusinessOrInteractiveEnglishRouteImport.update({
    id: '/spoken-business-or-interactive-english',
    path: '/spoken-business-or-interactive-english',
    getParentRoute: () => rootRouteImport,
  } as any)
const SpokenEnglishClassesAhmedabadRoute =
  SpokenEnglishClassesAhmedabadRouteImport.update({
    id: '/spoken-english-classes-ahmedabad',
    path: '/spoken-english-classes-ahmedabad',
    getParentRoute: () => rootRouteImport,
  } as any)
const SpokenEnglishClassesBengaluruRoute =
  SpokenEnglishClassesBengaluruRouteImport.update({
    id: '/spoken-english-classes-bengaluru',
    path: '/spoken-english-classes-bengaluru',
    getParentRoute: () => rootRouteImport,
  } as any)
const SpokenEnglishClassesChennaiRoute =
  SpokenEnglishClassesChennaiRouteImport.update({
    id: '/spoken-english-classes-chennai',
    path: '/spoken-english-classes-chennai',
    getParentRoute: () => rootRouteImport,
  } as any)
const SpokenEnglishClassesCoimbatoreRoute =
  SpokenEnglishClassesCoimbatoreRouteImport.update({
    id: '/spoken-english-classes-coimbatore',
    path: '/spoken-english-classes-coimbatore',
    getParentRoute: () => rootRouteImport,
  } as any)
const SpokenEnglishClassesDelhiRoute =
  SpokenEnglishClassesDelhiRouteImport.update({
    id: '/spoken-english-classes-delhi',
    path: '/spoken-english-classes-delhi',
    getParentRoute: () => rootRouteImport,
  } as any)
const SpokenEnglishClassesGuwahatiRoute =
  SpokenEnglishClassesGuwahatiRouteImport.update({
    id: '/spoken-english-classes-guwahati',
    path: '/spoken-english-classes-guwahati',
    getParentRoute: () => rootRouteImport,
  } as any)
const SpokenEnglishClassesHyderabadRoute =
  SpokenEnglishClassesHyderabadRouteImport.update({
    id: '/spoken-english-classes-hyderabad',
    path: '/spoken-english-classes-hyderabad',
    getParentRoute: () => rootRouteImport,
  } as any)
const SpokenEnglishClassesKochiRoute =
  SpokenEnglishClassesKochiRouteImport.update({
    id: '/spoken-english-classes-kochi',
    path: '/spoken-english-classes-kochi',
    getParentRoute: () => rootRouteImport,
  } as any)
const SpokenEnglishClassesKolkataRoute =
  SpokenEnglishClassesKolkataRouteImport.update({
    id: '/spoken-english-classes-kolkata',
    path: '/spoken-english-classes-kolkata',
    getParentRoute: () => rootRouteImport,
  } as any)
const SpokenEnglishClassesMumbaiRoute =
  SpokenEnglishClassesMumbaiRouteImport.update({
    id: '/spoken-english-classes-mumbai',
    path: '/spoken-english-classes-mumbai',
    getParentRoute: () => rootRouteImport,
  } as any)
const SpokenEnglishClassesNagpurRoute =
  SpokenEnglishClassesNagpurRouteImport.update({
    id: '/spoken-english-classes-nagpur',
    path: '/spoken-english-classes-nagpur',
    getParentRoute: () => rootRouteImport,
  } as any)
const SpokenEnglishClassesPatnaRoute =
  SpokenEnglishClassesPatnaRouteImport.update({
    id: '/spoken-english-classes-patna',
    path: '/spoken-english-classes-patna',
    getParentRoute: () => rootRouteImport,
  } as any)
const SpokenEnglishClassesPuneRoute =
  SpokenEnglishClassesPuneRouteImport.update({
    id: '/spoken-english-classes-pune',
    path: '/spoken-english-classes-pune',
    getParentRoute: () => rootRouteImport,
  } as any)
const SpokenEnglishClassesSuratRoute =
  SpokenEnglishClassesSuratRouteImport.update({
    id: '/spoken-english-classes-surat',
    path: '/spoken-english-classes-surat',
    getParentRoute: () => rootRouteImport,
  } as any)
const SpokenEnglishClassesVisakhapatnamRoute =
  SpokenEnglishClassesVisakhapatnamRouteImport.update({
    id: '/spoken-english-classes-visakhapatnam',
    path: '/spoken-english-classes-visakhapatnam',
    getParentRoute: () => rootRouteImport,
  } as any)
const SpokenEnglishForBeginnersIndiaRoute =
  SpokenEnglishForBeginnersIndiaRouteImport.update({
    id: '/spoken-english-for-beginners-india',
    path: '/spoken-english-for-beginners-india',
    getParentRoute: () => rootRouteImport,
  } as any)
const SpokenEnglishForFreshersIndiaRoute =
  SpokenEnglishForFreshersIndiaRouteImport.update({
    id: '/spoken-english-for-freshers-india',
    path: '/spoken-english-for-freshers-india',
    getParentRoute: () => rootRouteImport,
  } as any)
const SpokenEnglishForHomemakersIndiaRoute =
  SpokenEnglishForHomemakersIndiaRouteImport.update({
    id: '/spoken-english-for-homemakers-india',
    path: '/spoken-english-for-homemakers-india',
    getParentRoute: () => rootRouteImport,
  } as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyUsRoute = WhyUsRouteImport.update({
  id: '/why-us',
  path: '/why-us',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkplaceEnglishCourseOnlineIndiaRoute =
  WorkplaceEnglishCourseOnlineIndiaRouteImport.update({
    id: '/workplace-english-course-online-india',
    path: '/workplace-english-course-online-india',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/best-online-spoken-english-classes-india': typeof BestOnlineSpokenEnglishClassesIndiaRoute
  '/book-free-demo': typeof BookFreeDemoRoute
  '/course-business-english': typeof CourseBusinessEnglishRoute
  '/course-career-counselling': typeof CourseCareerCounsellingRoute
  '/course-ielts': typeof CourseIeltsRoute
  '/course-interactive-speaking': typeof CourseInteractiveSpeakingRoute
  '/course-interview-prep': typeof CourseInterviewPrepRoute
  '/course-kids-english': typeof CourseKidsEnglishRoute
  '/course-spoken-english': typeof CourseSpokenEnglishRoute
  '/english-career': typeof EnglishCareerRoute
  '/english-class-fees-india': typeof EnglishClassFeesIndiaRoute
  '/english-for-client-calls-india': typeof EnglishForClientCallsIndiaRoute
  '/english-for-it-professionals-india': typeof EnglishForItProfessionalsIndiaRoute
  '/english-for-presentations-india': typeof EnglishForPresentationsIndiaRoute
  '/english-for-working-professionals-india': typeof EnglishForWorkingProfessionalsIndiaRoute
  '/english-hindi-bengali-medium': typeof EnglishHindiBengaliMediumRoute
  '/english-institute-comparison-india': typeof EnglishInstituteComparisonIndiaRoute
  '/founder': typeof FounderRoute
  '/free-english-speaking-practice-vs-paid-class': typeof FreeEnglishSpeakingPracticeVsPaidClassRoute
  '/guides': typeof GuidesRoute
  '/how-long-to-learn-spoken-english': typeof HowLongToLearnSpokenEnglishRoute
  '/how-to-speak-english-fluently': typeof HowToSpeakEnglishFluentlyRoute
  '/ielts-coaching-fees-india': typeof IeltsCoachingFeesIndiaRoute
  '/interactive-english-class-hesitation': typeof InteractiveEnglishClassHesitationRoute
  '/online-vs-offline-spoken-english-classes': typeof OnlineVsOfflineSpokenEnglishClassesRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/spoken-business-or-interactive-english': typeof SpokenBusinessOrInteractiveEnglishRoute
  '/spoken-english-classes-ahmedabad': typeof SpokenEnglishClassesAhmedabadRoute
  '/spoken-english-classes-bengaluru': typeof SpokenEnglishClassesBengaluruRoute
  '/spoken-english-classes-chennai': typeof SpokenEnglishClassesChennaiRoute
  '/spoken-english-classes-coimbatore': typeof SpokenEnglishClassesCoimbatoreRoute
  '/spoken-english-classes-delhi': typeof SpokenEnglishClassesDelhiRoute
  '/spoken-english-classes-guwahati': typeof SpokenEnglishClassesGuwahatiRoute
  '/spoken-english-classes-hyderabad': typeof SpokenEnglishClassesHyderabadRoute
  '/spoken-english-classes-kochi': typeof SpokenEnglishClassesKochiRoute
  '/spoken-english-classes-kolkata': typeof SpokenEnglishClassesKolkataRoute
  '/spoken-english-classes-mumbai': typeof SpokenEnglishClassesMumbaiRoute
  '/spoken-english-classes-nagpur': typeof SpokenEnglishClassesNagpurRoute
  '/spoken-english-classes-patna': typeof SpokenEnglishClassesPatnaRoute
  '/spoken-english-classes-pune': typeof SpokenEnglishClassesPuneRoute
  '/spoken-english-classes-surat': typeof SpokenEnglishClassesSuratRoute
  '/spoken-english-classes-visakhapatnam': typeof SpokenEnglishClassesVisakhapatnamRoute
  '/spoken-english-for-beginners-india': typeof SpokenEnglishForBeginnersIndiaRoute
  '/spoken-english-for-freshers-india': typeof SpokenEnglishForFreshersIndiaRoute
  '/spoken-english-for-homemakers-india': typeof SpokenEnglishForHomemakersIndiaRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
  '/why-us': typeof WhyUsRoute
  '/workplace-english-course-online-india': typeof WorkplaceEnglishCourseOnlineIndiaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/best-online-spoken-english-classes-india': typeof BestOnlineSpokenEnglishClassesIndiaRoute
  '/book-free-demo': typeof BookFreeDemoRoute
  '/course-business-english': typeof CourseBusinessEnglishRoute
  '/course-career-counselling': typeof CourseCareerCounsellingRoute
  '/course-ielts': typeof CourseIeltsRoute
  '/course-interactive-speaking': typeof CourseInteractiveSpeakingRoute
  '/course-interview-prep': typeof CourseInterviewPrepRoute
  '/course-kids-english': typeof CourseKidsEnglishRoute
  '/course-spoken-english': typeof CourseSpokenEnglishRoute
  '/english-career': typeof EnglishCareerRoute
  '/english-class-fees-india': typeof EnglishClassFeesIndiaRoute
  '/english-for-client-calls-india': typeof EnglishForClientCallsIndiaRoute
  '/english-for-it-professionals-india': typeof EnglishForItProfessionalsIndiaRoute
  '/english-for-presentations-india': typeof EnglishForPresentationsIndiaRoute
  '/english-for-working-professionals-india': typeof EnglishForWorkingProfessionalsIndiaRoute
  '/english-hindi-bengali-medium': typeof EnglishHindiBengaliMediumRoute
  '/english-institute-comparison-india': typeof EnglishInstituteComparisonIndiaRoute
  '/founder': typeof FounderRoute
  '/free-english-speaking-practice-vs-paid-class': typeof FreeEnglishSpeakingPracticeVsPaidClassRoute
  '/guides': typeof GuidesRoute
  '/how-long-to-learn-spoken-english': typeof HowLongToLearnSpokenEnglishRoute
  '/how-to-speak-english-fluently': typeof HowToSpeakEnglishFluentlyRoute
  '/ielts-coaching-fees-india': typeof IeltsCoachingFeesIndiaRoute
  '/interactive-english-class-hesitation': typeof InteractiveEnglishClassHesitationRoute
  '/online-vs-offline-spoken-english-classes': typeof OnlineVsOfflineSpokenEnglishClassesRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/spoken-business-or-interactive-english': typeof SpokenBusinessOrInteractiveEnglishRoute
  '/spoken-english-classes-ahmedabad': typeof SpokenEnglishClassesAhmedabadRoute
  '/spoken-english-classes-bengaluru': typeof SpokenEnglishClassesBengaluruRoute
  '/spoken-english-classes-chennai': typeof SpokenEnglishClassesChennaiRoute
  '/spoken-english-classes-coimbatore': typeof SpokenEnglishClassesCoimbatoreRoute
  '/spoken-english-classes-delhi': typeof SpokenEnglishClassesDelhiRoute
  '/spoken-english-classes-guwahati': typeof SpokenEnglishClassesGuwahatiRoute
  '/spoken-english-classes-hyderabad': typeof SpokenEnglishClassesHyderabadRoute
  '/spoken-english-classes-kochi': typeof SpokenEnglishClassesKochiRoute
  '/spoken-english-classes-kolkata': typeof SpokenEnglishClassesKolkataRoute
  '/spoken-english-classes-mumbai': typeof SpokenEnglishClassesMumbaiRoute
  '/spoken-english-classes-nagpur': typeof SpokenEnglishClassesNagpurRoute
  '/spoken-english-classes-patna': typeof SpokenEnglishClassesPatnaRoute
  '/spoken-english-classes-pune': typeof SpokenEnglishClassesPuneRoute
  '/spoken-english-classes-surat': typeof SpokenEnglishClassesSuratRoute
  '/spoken-english-classes-visakhapatnam': typeof SpokenEnglishClassesVisakhapatnamRoute
  '/spoken-english-for-beginners-india': typeof SpokenEnglishForBeginnersIndiaRoute
  '/spoken-english-for-freshers-india': typeof SpokenEnglishForFreshersIndiaRoute
  '/spoken-english-for-homemakers-india': typeof SpokenEnglishForHomemakersIndiaRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
  '/why-us': typeof WhyUsRoute
  '/workplace-english-course-online-india': typeof WorkplaceEnglishCourseOnlineIndiaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/best-online-spoken-english-classes-india': typeof BestOnlineSpokenEnglishClassesIndiaRoute
  '/book-free-demo': typeof BookFreeDemoRoute
  '/course-business-english': typeof CourseBusinessEnglishRoute
  '/course-career-counselling': typeof CourseCareerCounsellingRoute
  '/course-ielts': typeof CourseIeltsRoute
  '/course-interactive-speaking': typeof CourseInteractiveSpeakingRoute
  '/course-interview-prep': typeof CourseInterviewPrepRoute
  '/course-kids-english': typeof CourseKidsEnglishRoute
  '/course-spoken-english': typeof CourseSpokenEnglishRoute
  '/english-career': typeof EnglishCareerRoute
  '/english-class-fees-india': typeof EnglishClassFeesIndiaRoute
  '/english-for-client-calls-india': typeof EnglishForClientCallsIndiaRoute
  '/english-for-it-professionals-india': typeof EnglishForItProfessionalsIndiaRoute
  '/english-for-presentations-india': typeof EnglishForPresentationsIndiaRoute
  '/english-for-working-professionals-india': typeof EnglishForWorkingProfessionalsIndiaRoute
  '/english-hindi-bengali-medium': typeof EnglishHindiBengaliMediumRoute
  '/english-institute-comparison-india': typeof EnglishInstituteComparisonIndiaRoute
  '/founder': typeof FounderRoute
  '/free-english-speaking-practice-vs-paid-class': typeof FreeEnglishSpeakingPracticeVsPaidClassRoute
  '/guides': typeof GuidesRoute
  '/how-long-to-learn-spoken-english': typeof HowLongToLearnSpokenEnglishRoute
  '/how-to-speak-english-fluently': typeof HowToSpeakEnglishFluentlyRoute
  '/ielts-coaching-fees-india': typeof IeltsCoachingFeesIndiaRoute
  '/interactive-english-class-hesitation': typeof InteractiveEnglishClassHesitationRoute
  '/online-vs-offline-spoken-english-classes': typeof OnlineVsOfflineSpokenEnglishClassesRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/spoken-business-or-interactive-english': typeof SpokenBusinessOrInteractiveEnglishRoute
  '/spoken-english-classes-ahmedabad': typeof SpokenEnglishClassesAhmedabadRoute
  '/spoken-english-classes-bengaluru': typeof SpokenEnglishClassesBengaluruRoute
  '/spoken-english-classes-chennai': typeof SpokenEnglishClassesChennaiRoute
  '/spoken-english-classes-coimbatore': typeof SpokenEnglishClassesCoimbatoreRoute
  '/spoken-english-classes-delhi': typeof SpokenEnglishClassesDelhiRoute
  '/spoken-english-classes-guwahati': typeof SpokenEnglishClassesGuwahatiRoute
  '/spoken-english-classes-hyderabad': typeof SpokenEnglishClassesHyderabadRoute
  '/spoken-english-classes-kochi': typeof SpokenEnglishClassesKochiRoute
  '/spoken-english-classes-kolkata': typeof SpokenEnglishClassesKolkataRoute
  '/spoken-english-classes-mumbai': typeof SpokenEnglishClassesMumbaiRoute
  '/spoken-english-classes-nagpur': typeof SpokenEnglishClassesNagpurRoute
  '/spoken-english-classes-patna': typeof SpokenEnglishClassesPatnaRoute
  '/spoken-english-classes-pune': typeof SpokenEnglishClassesPuneRoute
  '/spoken-english-classes-surat': typeof SpokenEnglishClassesSuratRoute
  '/spoken-english-classes-visakhapatnam': typeof SpokenEnglishClassesVisakhapatnamRoute
  '/spoken-english-for-beginners-india': typeof SpokenEnglishForBeginnersIndiaRoute
  '/spoken-english-for-freshers-india': typeof SpokenEnglishForFreshersIndiaRoute
  '/spoken-english-for-homemakers-india': typeof SpokenEnglishForHomemakersIndiaRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
  '/why-us': typeof WhyUsRoute
  '/workplace-english-course-online-india': typeof WorkplaceEnglishCourseOnlineIndiaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/best-online-spoken-english-classes-india'
    | '/book-free-demo'
    | '/course-business-english'
    | '/course-career-counselling'
    | '/course-ielts'
    | '/course-interactive-speaking'
    | '/course-interview-prep'
    | '/course-kids-english'
    | '/course-spoken-english'
    | '/english-career'
    | '/english-class-fees-india'
    | '/english-for-client-calls-india'
    | '/english-for-it-professionals-india'
    | '/english-for-presentations-india'
    | '/english-for-working-professionals-india'
    | '/english-hindi-bengali-medium'
    | '/english-institute-comparison-india'
    | '/founder'
    | '/free-english-speaking-practice-vs-paid-class'
    | '/guides'
    | '/how-long-to-learn-spoken-english'
    | '/how-to-speak-english-fluently'
    | '/ielts-coaching-fees-india'
    | '/interactive-english-class-hesitation'
    | '/online-vs-offline-spoken-english-classes'
    | '/privacy'
    | '/refunds'
    | '/spoken-business-or-interactive-english'
    | '/spoken-english-classes-ahmedabad'
    | '/spoken-english-classes-bengaluru'
    | '/spoken-english-classes-chennai'
    | '/spoken-english-classes-coimbatore'
    | '/spoken-english-classes-delhi'
    | '/spoken-english-classes-guwahati'
    | '/spoken-english-classes-hyderabad'
    | '/spoken-english-classes-kochi'
    | '/spoken-english-classes-kolkata'
    | '/spoken-english-classes-mumbai'
    | '/spoken-english-classes-nagpur'
    | '/spoken-english-classes-patna'
    | '/spoken-english-classes-pune'
    | '/spoken-english-classes-surat'
    | '/spoken-english-classes-visakhapatnam'
    | '/spoken-english-for-beginners-india'
    | '/spoken-english-for-freshers-india'
    | '/spoken-english-for-homemakers-india'
    | '/success-stories'
    | '/terms'
    | '/why-us'
    | '/workplace-english-course-online-india'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/best-online-spoken-english-classes-india'
    | '/book-free-demo'
    | '/course-business-english'
    | '/course-career-counselling'
    | '/course-ielts'
    | '/course-interactive-speaking'
    | '/course-interview-prep'
    | '/course-kids-english'
    | '/course-spoken-english'
    | '/english-career'
    | '/english-class-fees-india'
    | '/english-for-client-calls-india'
    | '/english-for-it-professionals-india'
    | '/english-for-presentations-india'
    | '/english-for-working-professionals-india'
    | '/english-hindi-bengali-medium'
    | '/english-institute-comparison-india'
    | '/founder'
    | '/free-english-speaking-practice-vs-paid-class'
    | '/guides'
    | '/how-long-to-learn-spoken-english'
    | '/how-to-speak-english-fluently'
    | '/ielts-coaching-fees-india'
    | '/interactive-english-class-hesitation'
    | '/online-vs-offline-spoken-english-classes'
    | '/privacy'
    | '/refunds'
    | '/spoken-business-or-interactive-english'
    | '/spoken-english-classes-ahmedabad'
    | '/spoken-english-classes-bengaluru'
    | '/spoken-english-classes-chennai'
    | '/spoken-english-classes-coimbatore'
    | '/spoken-english-classes-delhi'
    | '/spoken-english-classes-guwahati'
    | '/spoken-english-classes-hyderabad'
    | '/spoken-english-classes-kochi'
    | '/spoken-english-classes-kolkata'
    | '/spoken-english-classes-mumbai'
    | '/spoken-english-classes-nagpur'
    | '/spoken-english-classes-patna'
    | '/spoken-english-classes-pune'
    | '/spoken-english-classes-surat'
    | '/spoken-english-classes-visakhapatnam'
    | '/spoken-english-for-beginners-india'
    | '/spoken-english-for-freshers-india'
    | '/spoken-english-for-homemakers-india'
    | '/success-stories'
    | '/terms'
    | '/why-us'
    | '/workplace-english-course-online-india'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/best-online-spoken-english-classes-india'
    | '/book-free-demo'
    | '/course-business-english'
    | '/course-career-counselling'
    | '/course-ielts'
    | '/course-interactive-speaking'
    | '/course-interview-prep'
    | '/course-kids-english'
    | '/course-spoken-english'
    | '/english-career'
    | '/english-class-fees-india'
    | '/english-for-client-calls-india'
    | '/english-for-it-professionals-india'
    | '/english-for-presentations-india'
    | '/english-for-working-professionals-india'
    | '/english-hindi-bengali-medium'
    | '/english-institute-comparison-india'
    | '/founder'
    | '/free-english-speaking-practice-vs-paid-class'
    | '/guides'
    | '/how-long-to-learn-spoken-english'
    | '/how-to-speak-english-fluently'
    | '/ielts-coaching-fees-india'
    | '/interactive-english-class-hesitation'
    | '/online-vs-offline-spoken-english-classes'
    | '/privacy'
    | '/refunds'
    | '/spoken-business-or-interactive-english'
    | '/spoken-english-classes-ahmedabad'
    | '/spoken-english-classes-bengaluru'
    | '/spoken-english-classes-chennai'
    | '/spoken-english-classes-coimbatore'
    | '/spoken-english-classes-delhi'
    | '/spoken-english-classes-guwahati'
    | '/spoken-english-classes-hyderabad'
    | '/spoken-english-classes-kochi'
    | '/spoken-english-classes-kolkata'
    | '/spoken-english-classes-mumbai'
    | '/spoken-english-classes-nagpur'
    | '/spoken-english-classes-patna'
    | '/spoken-english-classes-pune'
    | '/spoken-english-classes-surat'
    | '/spoken-english-classes-visakhapatnam'
    | '/spoken-english-for-beginners-india'
    | '/spoken-english-for-freshers-india'
    | '/spoken-english-for-homemakers-india'
    | '/success-stories'
    | '/terms'
    | '/why-us'
    | '/workplace-english-course-online-india'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  BestOnlineSpokenEnglishClassesIndiaRoute: typeof BestOnlineSpokenEnglishClassesIndiaRoute
  BookFreeDemoRoute: typeof BookFreeDemoRoute
  CourseBusinessEnglishRoute: typeof CourseBusinessEnglishRoute
  CourseCareerCounsellingRoute: typeof CourseCareerCounsellingRoute
  CourseIeltsRoute: typeof CourseIeltsRoute
  CourseInteractiveSpeakingRoute: typeof CourseInteractiveSpeakingRoute
  CourseInterviewPrepRoute: typeof CourseInterviewPrepRoute
  CourseKidsEnglishRoute: typeof CourseKidsEnglishRoute
  CourseSpokenEnglishRoute: typeof CourseSpokenEnglishRoute
  EnglishCareerRoute: typeof EnglishCareerRoute
  EnglishClassFeesIndiaRoute: typeof EnglishClassFeesIndiaRoute
  EnglishForClientCallsIndiaRoute: typeof EnglishForClientCallsIndiaRoute
  EnglishForItProfessionalsIndiaRoute: typeof EnglishForItProfessionalsIndiaRoute
  EnglishForPresentationsIndiaRoute: typeof EnglishForPresentationsIndiaRoute
  EnglishForWorkingProfessionalsIndiaRoute: typeof EnglishForWorkingProfessionalsIndiaRoute
  EnglishHindiBengaliMediumRoute: typeof EnglishHindiBengaliMediumRoute
  EnglishInstituteComparisonIndiaRoute: typeof EnglishInstituteComparisonIndiaRoute
  FounderRoute: typeof FounderRoute
  FreeEnglishSpeakingPracticeVsPaidClassRoute: typeof FreeEnglishSpeakingPracticeVsPaidClassRoute
  GuidesRoute: typeof GuidesRoute
  HowLongToLearnSpokenEnglishRoute: typeof HowLongToLearnSpokenEnglishRoute
  HowToSpeakEnglishFluentlyRoute: typeof HowToSpeakEnglishFluentlyRoute
  IeltsCoachingFeesIndiaRoute: typeof IeltsCoachingFeesIndiaRoute
  InteractiveEnglishClassHesitationRoute: typeof InteractiveEnglishClassHesitationRoute
  OnlineVsOfflineSpokenEnglishClassesRoute: typeof OnlineVsOfflineSpokenEnglishClassesRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  SpokenBusinessOrInteractiveEnglishRoute: typeof SpokenBusinessOrInteractiveEnglishRoute
  SpokenEnglishClassesAhmedabadRoute: typeof SpokenEnglishClassesAhmedabadRoute
  SpokenEnglishClassesBengaluruRoute: typeof SpokenEnglishClassesBengaluruRoute
  SpokenEnglishClassesChennaiRoute: typeof SpokenEnglishClassesChennaiRoute
  SpokenEnglishClassesCoimbatoreRoute: typeof SpokenEnglishClassesCoimbatoreRoute
  SpokenEnglishClassesDelhiRoute: typeof SpokenEnglishClassesDelhiRoute
  SpokenEnglishClassesGuwahatiRoute: typeof SpokenEnglishClassesGuwahatiRoute
  SpokenEnglishClassesHyderabadRoute: typeof SpokenEnglishClassesHyderabadRoute
  SpokenEnglishClassesKochiRoute: typeof SpokenEnglishClassesKochiRoute
  SpokenEnglishClassesKolkataRoute: typeof SpokenEnglishClassesKolkataRoute
  SpokenEnglishClassesMumbaiRoute: typeof SpokenEnglishClassesMumbaiRoute
  SpokenEnglishClassesNagpurRoute: typeof SpokenEnglishClassesNagpurRoute
  SpokenEnglishClassesPatnaRoute: typeof SpokenEnglishClassesPatnaRoute
  SpokenEnglishClassesPuneRoute: typeof SpokenEnglishClassesPuneRoute
  SpokenEnglishClassesSuratRoute: typeof SpokenEnglishClassesSuratRoute
  SpokenEnglishClassesVisakhapatnamRoute: typeof SpokenEnglishClassesVisakhapatnamRoute
  SpokenEnglishForBeginnersIndiaRoute: typeof SpokenEnglishForBeginnersIndiaRoute
  SpokenEnglishForFreshersIndiaRoute: typeof SpokenEnglishForFreshersIndiaRoute
  SpokenEnglishForHomemakersIndiaRoute: typeof SpokenEnglishForHomemakersIndiaRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  TermsRoute: typeof TermsRoute
  WhyUsRoute: typeof WhyUsRoute
  WorkplaceEnglishCourseOnlineIndiaRoute: typeof WorkplaceEnglishCourseOnlineIndiaRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-online-spoken-english-classes-india': {
      id: '/best-online-spoken-english-classes-india'
      path: '/best-online-spoken-english-classes-india'
      fullPath: '/best-online-spoken-english-classes-india'
      preLoaderRoute: typeof BestOnlineSpokenEnglishClassesIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-free-demo': {
      id: '/book-free-demo'
      path: '/book-free-demo'
      fullPath: '/book-free-demo'
      preLoaderRoute: typeof BookFreeDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course-business-english': {
      id: '/course-business-english'
      path: '/course-business-english'
      fullPath: '/course-business-english'
      preLoaderRoute: typeof CourseBusinessEnglishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course-career-counselling': {
      id: '/course-career-counselling'
      path: '/course-career-counselling'
      fullPath: '/course-career-counselling'
      preLoaderRoute: typeof CourseCareerCounsellingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course-ielts': {
      id: '/course-ielts'
      path: '/course-ielts'
      fullPath: '/course-ielts'
      preLoaderRoute: typeof CourseIeltsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course-interactive-speaking': {
      id: '/course-interactive-speaking'
      path: '/course-interactive-speaking'
      fullPath: '/course-interactive-speaking'
      preLoaderRoute: typeof CourseInteractiveSpeakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course-interview-prep': {
      id: '/course-interview-prep'
      path: '/course-interview-prep'
      fullPath: '/course-interview-prep'
      preLoaderRoute: typeof CourseInterviewPrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course-kids-english': {
      id: '/course-kids-english'
      path: '/course-kids-english'
      fullPath: '/course-kids-english'
      preLoaderRoute: typeof CourseKidsEnglishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course-spoken-english': {
      id: '/course-spoken-english'
      path: '/course-spoken-english'
      fullPath: '/course-spoken-english'
      preLoaderRoute: typeof CourseSpokenEnglishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english-career': {
      id: '/english-career'
      path: '/english-career'
      fullPath: '/english-career'
      preLoaderRoute: typeof EnglishCareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english-class-fees-india': {
      id: '/english-class-fees-india'
      path: '/english-class-fees-india'
      fullPath: '/english-class-fees-india'
      preLoaderRoute: typeof EnglishClassFeesIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english-for-client-calls-india': {
      id: '/english-for-client-calls-india'
      path: '/english-for-client-calls-india'
      fullPath: '/english-for-client-calls-india'
      preLoaderRoute: typeof EnglishForClientCallsIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english-for-it-professionals-india': {
      id: '/english-for-it-professionals-india'
      path: '/english-for-it-professionals-india'
      fullPath: '/english-for-it-professionals-india'
      preLoaderRoute: typeof EnglishForItProfessionalsIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english-for-presentations-india': {
      id: '/english-for-presentations-india'
      path: '/english-for-presentations-india'
      fullPath: '/english-for-presentations-india'
      preLoaderRoute: typeof EnglishForPresentationsIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english-for-working-professionals-india': {
      id: '/english-for-working-professionals-india'
      path: '/english-for-working-professionals-india'
      fullPath: '/english-for-working-professionals-india'
      preLoaderRoute: typeof EnglishForWorkingProfessionalsIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english-hindi-bengali-medium': {
      id: '/english-hindi-bengali-medium'
      path: '/english-hindi-bengali-medium'
      fullPath: '/english-hindi-bengali-medium'
      preLoaderRoute: typeof EnglishHindiBengaliMediumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english-institute-comparison-india': {
      id: '/english-institute-comparison-india'
      path: '/english-institute-comparison-india'
      fullPath: '/english-institute-comparison-india'
      preLoaderRoute: typeof EnglishInstituteComparisonIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-english-speaking-practice-vs-paid-class': {
      id: '/free-english-speaking-practice-vs-paid-class'
      path: '/free-english-speaking-practice-vs-paid-class'
      fullPath: '/free-english-speaking-practice-vs-paid-class'
      preLoaderRoute: typeof FreeEnglishSpeakingPracticeVsPaidClassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-long-to-learn-spoken-english': {
      id: '/how-long-to-learn-spoken-english'
      path: '/how-long-to-learn-spoken-english'
      fullPath: '/how-long-to-learn-spoken-english'
      preLoaderRoute: typeof HowLongToLearnSpokenEnglishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-speak-english-fluently': {
      id: '/how-to-speak-english-fluently'
      path: '/how-to-speak-english-fluently'
      fullPath: '/how-to-speak-english-fluently'
      preLoaderRoute: typeof HowToSpeakEnglishFluentlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ielts-coaching-fees-india': {
      id: '/ielts-coaching-fees-india'
      path: '/ielts-coaching-fees-india'
      fullPath: '/ielts-coaching-fees-india'
      preLoaderRoute: typeof IeltsCoachingFeesIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interactive-english-class-hesitation': {
      id: '/interactive-english-class-hesitation'
      path: '/interactive-english-class-hesitation'
      fullPath: '/interactive-english-class-hesitation'
      preLoaderRoute: typeof InteractiveEnglishClassHesitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-vs-offline-spoken-english-classes': {
      id: '/online-vs-offline-spoken-english-classes'
      path: '/online-vs-offline-spoken-english-classes'
      fullPath: '/online-vs-offline-spoken-english-classes'
      preLoaderRoute: typeof OnlineVsOfflineSpokenEnglishClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoken-business-or-interactive-english': {
      id: '/spoken-business-or-interactive-english'
      path: '/spoken-business-or-interactive-english'
      fullPath: '/spoken-business-or-interactive-english'
      preLoaderRoute: typeof SpokenBusinessOrInteractiveEnglishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoken-english-classes-ahmedabad': {
      id: '/spoken-english-classes-ahmedabad'
      path: '/spoken-english-classes-ahmedabad'
      fullPath: '/spoken-english-classes-ahmedabad'
      preLoaderRoute: typeof SpokenEnglishClassesAhmedabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoken-english-classes-bengaluru': {
      id: '/spoken-english-classes-bengaluru'
      path: '/spoken-english-classes-bengaluru'
      fullPath: '/spoken-english-classes-bengaluru'
      preLoaderRoute: typeof SpokenEnglishClassesBengaluruRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoken-english-classes-chennai': {
      id: '/spoken-english-classes-chennai'
      path: '/spoken-english-classes-chennai'
      fullPath: '/spoken-english-classes-chennai'
      preLoaderRoute: typeof SpokenEnglishClassesChennaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoken-english-classes-coimbatore': {
      id: '/spoken-english-classes-coimbatore'
      path: '/spoken-english-classes-coimbatore'
      fullPath: '/spoken-english-classes-coimbatore'
      preLoaderRoute: typeof SpokenEnglishClassesCoimbatoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoken-english-classes-delhi': {
      id: '/spoken-english-classes-delhi'
      path: '/spoken-english-classes-delhi'
      fullPath: '/spoken-english-classes-delhi'
      preLoaderRoute: typeof SpokenEnglishClassesDelhiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoken-english-classes-guwahati': {
      id: '/spoken-english-classes-guwahati'
      path: '/spoken-english-classes-guwahati'
      fullPath: '/spoken-english-classes-guwahati'
      preLoaderRoute: typeof SpokenEnglishClassesGuwahatiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoken-english-classes-hyderabad': {
      id: '/spoken-english-classes-hyderabad'
      path: '/spoken-english-classes-hyderabad'
      fullPath: '/spoken-english-classes-hyderabad'
      preLoaderRoute: typeof SpokenEnglishClassesHyderabadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoken-english-classes-kochi': {
      id: '/spoken-english-classes-kochi'
      path: '/spoken-english-classes-kochi'
      fullPath: '/spoken-english-classes-kochi'
      preLoaderRoute: typeof SpokenEnglishClassesKochiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoken-english-classes-kolkata': {
      id: '/spoken-english-classes-kolkata'
      path: '/spoken-english-classes-kolkata'
      fullPath: '/spoken-english-classes-kolkata'
      preLoaderRoute: typeof SpokenEnglishClassesKolkataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoken-english-classes-mumbai': {
      id: '/spoken-english-classes-mumbai'
      path: '/spoken-english-classes-mumbai'
      fullPath: '/spoken-english-classes-mumbai'
      preLoaderRoute: typeof SpokenEnglishClassesMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoken-english-classes-nagpur': {
      id: '/spoken-english-classes-nagpur'
      path: '/spoken-english-classes-nagpur'
      fullPath: '/spoken-english-classes-nagpur'
      preLoaderRoute: typeof SpokenEnglishClassesNagpurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoken-english-classes-patna': {
      id: '/spoken-english-classes-patna'
      path: '/spoken-english-classes-patna'
      fullPath: '/spoken-english-classes-patna'
      preLoaderRoute: typeof SpokenEnglishClassesPatnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoken-english-classes-pune': {
      id: '/spoken-english-classes-pune'
      path: '/spoken-english-classes-pune'
      fullPath: '/spoken-english-classes-pune'
      preLoaderRoute: typeof SpokenEnglishClassesPuneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoken-english-classes-surat': {
      id: '/spoken-english-classes-surat'
      path: '/spoken-english-classes-surat'
      fullPath: '/spoken-english-classes-surat'
      preLoaderRoute: typeof SpokenEnglishClassesSuratRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoken-english-classes-visakhapatnam': {
      id: '/spoken-english-classes-visakhapatnam'
      path: '/spoken-english-classes-visakhapatnam'
      fullPath: '/spoken-english-classes-visakhapatnam'
      preLoaderRoute: typeof SpokenEnglishClassesVisakhapatnamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoken-english-for-beginners-india': {
      id: '/spoken-english-for-beginners-india'
      path: '/spoken-english-for-beginners-india'
      fullPath: '/spoken-english-for-beginners-india'
      preLoaderRoute: typeof SpokenEnglishForBeginnersIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoken-english-for-freshers-india': {
      id: '/spoken-english-for-freshers-india'
      path: '/spoken-english-for-freshers-india'
      fullPath: '/spoken-english-for-freshers-india'
      preLoaderRoute: typeof SpokenEnglishForFreshersIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spoken-english-for-homemakers-india': {
      id: '/spoken-english-for-homemakers-india'
      path: '/spoken-english-for-homemakers-india'
      fullPath: '/spoken-english-for-homemakers-india'
      preLoaderRoute: typeof SpokenEnglishForHomemakersIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-us': {
      id: '/why-us'
      path: '/why-us'
      fullPath: '/why-us'
      preLoaderRoute: typeof WhyUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workplace-english-course-online-india': {
      id: '/workplace-english-course-online-india'
      path: '/workplace-english-course-online-india'
      fullPath: '/workplace-english-course-online-india'
      preLoaderRoute: typeof WorkplaceEnglishCourseOnlineIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  BestOnlineSpokenEnglishClassesIndiaRoute:
    BestOnlineSpokenEnglishClassesIndiaRoute,
  BookFreeDemoRoute: BookFreeDemoRoute,
  CourseBusinessEnglishRoute: CourseBusinessEnglishRoute,
  CourseCareerCounsellingRoute: CourseCareerCounsellingRoute,
  CourseIeltsRoute: CourseIeltsRoute,
  CourseInteractiveSpeakingRoute: CourseInteractiveSpeakingRoute,
  CourseInterviewPrepRoute: CourseInterviewPrepRoute,
  CourseKidsEnglishRoute: CourseKidsEnglishRoute,
  CourseSpokenEnglishRoute: CourseSpokenEnglishRoute,
  EnglishCareerRoute: EnglishCareerRoute,
  EnglishClassFeesIndiaRoute: EnglishClassFeesIndiaRoute,
  EnglishForClientCallsIndiaRoute: EnglishForClientCallsIndiaRoute,
  EnglishForItProfessionalsIndiaRoute: EnglishForItProfessionalsIndiaRoute,
  EnglishForPresentationsIndiaRoute: EnglishForPresentationsIndiaRoute,
  EnglishForWorkingProfessionalsIndiaRoute:
    EnglishForWorkingProfessionalsIndiaRoute,
  EnglishHindiBengaliMediumRoute: EnglishHindiBengaliMediumRoute,
  EnglishInstituteComparisonIndiaRoute: EnglishInstituteComparisonIndiaRoute,
  FounderRoute: FounderRoute,
  FreeEnglishSpeakingPracticeVsPaidClassRoute:
    FreeEnglishSpeakingPracticeVsPaidClassRoute,
  GuidesRoute: GuidesRoute,
  HowLongToLearnSpokenEnglishRoute: HowLongToLearnSpokenEnglishRoute,
  HowToSpeakEnglishFluentlyRoute: HowToSpeakEnglishFluentlyRoute,
  IeltsCoachingFeesIndiaRoute: IeltsCoachingFeesIndiaRoute,
  InteractiveEnglishClassHesitationRoute:
    InteractiveEnglishClassHesitationRoute,
  OnlineVsOfflineSpokenEnglishClassesRoute:
    OnlineVsOfflineSpokenEnglishClassesRoute,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  SpokenBusinessOrInteractiveEnglishRoute:
    SpokenBusinessOrInteractiveEnglishRoute,
  SpokenEnglishClassesAhmedabadRoute: SpokenEnglishClassesAhmedabadRoute,
  SpokenEnglishClassesBengaluruRoute: SpokenEnglishClassesBengaluruRoute,
  SpokenEnglishClassesChennaiRoute: SpokenEnglishClassesChennaiRoute,
  SpokenEnglishClassesCoimbatoreRoute: SpokenEnglishClassesCoimbatoreRoute,
  SpokenEnglishClassesDelhiRoute: SpokenEnglishClassesDelhiRoute,
  SpokenEnglishClassesGuwahatiRoute: SpokenEnglishClassesGuwahatiRoute,
  SpokenEnglishClassesHyderabadRoute: SpokenEnglishClassesHyderabadRoute,
  SpokenEnglishClassesKochiRoute: SpokenEnglishClassesKochiRoute,
  SpokenEnglishClassesKolkataRoute: SpokenEnglishClassesKolkataRoute,
  SpokenEnglishClassesMumbaiRoute: SpokenEnglishClassesMumbaiRoute,
  SpokenEnglishClassesNagpurRoute: SpokenEnglishClassesNagpurRoute,
  SpokenEnglishClassesPatnaRoute: SpokenEnglishClassesPatnaRoute,
  SpokenEnglishClassesPuneRoute: SpokenEnglishClassesPuneRoute,
  SpokenEnglishClassesSuratRoute: SpokenEnglishClassesSuratRoute,
  SpokenEnglishClassesVisakhapatnamRoute:
    SpokenEnglishClassesVisakhapatnamRoute,
  SpokenEnglishForBeginnersIndiaRoute: SpokenEnglishForBeginnersIndiaRoute,
  SpokenEnglishForFreshersIndiaRoute: SpokenEnglishForFreshersIndiaRoute,
  SpokenEnglishForHomemakersIndiaRoute: SpokenEnglishForHomemakersIndiaRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
  TermsRoute: TermsRoute,
  WhyUsRoute: WhyUsRoute,
  WorkplaceEnglishCourseOnlineIndiaRoute:
    WorkplaceEnglishCourseOnlineIndiaRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
